export enum Action_types {
    GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS',
    GET_PRODUCTS_ERROR= 'GET_PRODUCTS_ERROR',
    GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS',

    CREATE_NEW_PRODUCT = 'CREATE_NEW_PRODUCT',
    CREATE_NEW_PRODUCT_ERROR = 'CREATE_NEW_PRODUCT_ERROR',
    CREATE_NEW_PRODUCT_SUCCESS = 'CREATE_NEW_PRODUCT_SUCCESS',

    UPDATE_EXISTS_PRODUCT = 'UPDATE_EXISTS_PRODUCT',
    UPDATE_EXISTS_PRODUCT_ERROR = 'UPDATE_EXISTS_PRODUCT_ERROR',
    UPDATE_EXISTS_PRODUCT_SUCCESS = 'UPDATE_EXISTS_PRODUCT_SUCCESS',

    DELETE_EXISTS_PRODUCT = 'DELETE_EXISTS_PRODUCT',

    GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES',
    GET_ALL_CATEGORIES_ERROR = 'GET_ALL_CATEGORIES_ERROR',
    GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS',

    GET_PRODUCTS_IN_CATEGORY = 'GET_PRODUCTS_IN_CATEGORY',
    GET_PRODUCTS_IN_CATEGORY_ERROR = 'GET_PRODUCTS_IN_CATEGORY_ERROR',
    GET_PRODUCTS_IN_CATEGORY_SUCCESS = 'GET_PRODUCTS_IN_CATEGORY_SUCCESS',

    FILTER_PRODUCTS_BY_CATEGORY = 'FILTER_PRODUCTS_BY_CATEGORY',

    RESET_PRODUCTS_FILTER = 'RESET_PRODUCTS_FILTER'

}
