export enum Action_types {
    GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS',
    GET_PRODUCTS_ERROR= 'GET_PRODUCTS_ERROR',
    GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS',

    CREATE_NEW_PRODUCT = 'CREATE_NEW_PRODUCT',
    CREATE_NEW_PRODUCT_ERROR = 'CREATE_NEW_PRODUCT_ERROR',
    CREATE_NEW_PRODUCT_SUCCESS = 'CREATE_NEW_PRODUCT_SUCCESS',

    GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES',
    GET_ALL_CATEGORIES_ERROR = 'GET_ALL_CATEGORIES_ERROR',
    GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS',

    GET_PRODUCTS_IN_CATEGORY = 'GET_PRODUCTS_IN_CATEGORY',
    GET_PRODUCTS_IN_CATEGORY_ERROR = 'GET_PRODUCTS_IN_CATEGORY_ERROR',
    GET_PRODUCTS_IN_CATEGORY_SUCCESS = 'GET_PRODUCTS_IN_CATEGORY_SUCCESS',

    FIND_PRODUCTS_BY_TITLE = 'FIND_PRODUCTS_BY_TITLE',
    FIND_PRODUCTS_BY_TITLE_ERROR = 'FIND_PRODUCTS_BY_ERROR',
    FIND_PRODUCTS_BY_TITLE_SUCCESS = 'FIND_PRODUCTS_BY__TITLE_SUCCESS'
}
